trigger:
-main

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

pool:
  vmImage: ubuntu-latest

variables:
  buildconfiguration:'Release'

steps:
- script: dotnet build --configuration $(buildconfiguration)
  displayName: 'dotnet build $(buildconfiguration)'